name: MGBowBash
main: com.comze_instancelabs.bowbash.Main
version: 1.3.5
author: InstanceLabs
softdepend: [Vault, MinigamesLib]
depend: [MinigamesLib]
loadbefore: [MinigamesLib]
commands:
   bb:
      description: Main command
      usage: /bb [action]
      aliases: [bowbash, mgbowbash]
