name: MGBowBash
main: com.comze_instancelabs.bowbash.Main
version: 1.0.1
author: InstanceLabs
softdepend: [Vault, MinigamesAPI]
depend: [MinigamesAPI]
loadbefore: [MinigamesAPI]
commands:
   bb:
      description: Main command
      usage: /bb [action]
      aliases: [bowbash, mgbowbash]
